apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: filestore
  name: filestore
  namespace: filestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestore
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: filestore
    spec:
      containers:
      - env:
        - name: DB_SOURCE
          value: root:root@tcp(mysql)/fileserver?charset=utf8&parseTime=true
        - name: OSSACCESSKEYID
          valueFrom:
            secretKeyRef:
              key: OSSACCESSKEYID
              name: osssecret
        - name: OSSACCESSKEYSECRET
          valueFrom:
            secretKeyRef:
              key: OSSACCESSKEYSECRET
              name: osssecret
        - name: RABBITURL
          value: amqp://guest:guest@rabbitmq:5672/
        - name: REDISHOST
          value: redis:6379
        - name: REDISPASS
          value: testupload
        image: csdengh/fileStore:d3341e09f77ec2eebea133cbb69d5cfcc0b70b82
        name: filestore
        ports:
        - containerPort: 80
        resources: {}
status: {}
